name: Linting and Building
description: This workflow runs on every push to the repository and performs linting and building tasks.
on: [push]

permissions:
  contents: write

jobs:
    Linting:
        name: Linting Job
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run mypy
              run: |
                mypy klogger.py --config-file .mypy.ini --show-error-codes --ignore-missing-imports
                if [ $? -ne 0 ]; then
                  echo "Mypy found errors."
                  exit 1
                fi
            
            - name: Run pylint
              run: |
                pylint klogger.py --output-format=json > pylint-report.json
                cat pylint-report.json
                # Fail if there are any errors (exit code >= 32)
                ERRORS=$(jq '[.[] | select(.type=="error")] | length' pylint-report.json)
                if [ "$ERRORS" -gt 0 ]; then
                echo "Pylint found $ERRORS errors."
                exit 1
                fi

    Building:
        name: Building Job
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        needs: Linting
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Build executable Windows
              if: matrix.os == 'windows-latest'
              run: |
                pyinstaller --onefile klogger.py
                if ($LASTEXITCODE -ne 0) {
                    Write-Host "Build failed."
                    exit 1
                }

            - name: Build executable Linux & Mac
              if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
              run: |
                pyinstaller --onefile klogger.py
                if [ $? -ne 0 ]; then
                  echo "Build failed."
                  exit 1
                fi

            - name: Archive build artifacts Windows
              if: matrix.os == 'windows-latest'
              uses: actions/upload-artifact@v4
              with:
                name: klogger
                path: dist/klogger.exe
                
            - name: Archive build artifacts Linux & Mac
              if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
              uses: actions/upload-artifact@v4
              with:
                name: klogger
                path: dist/klogger

            - name: Create GitHub Release Windows
              if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'windows-latest'
              uses: softprops/action-gh-release@v1
              with:
                files: dist/klogger.exe

            - name: Create GitHub Release Linux & Mac
              if: startsWith(github.ref, 'refs/tags/') && (matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest')
              uses: softprops/action-gh-release@v1
              with:
                files: dist/klogger
   